const BUILD_ENV = process.env.NEXT_PUBLIC_BUILD_ENV;
const IS_PRODUCTION = BUILD_ENV === "production";
const FULL_HOSTNAME = process.env.NEXT_PUBLIC_FULL_HOSTNAME;
const CRISP_TOKEN = process.env.NEXT_PUBLIC_CRISP_TOKEN;
const DEFAULT_THEME = "dark";
export { BUILD_ENV, IS_PRODUCTION, FULL_HOSTNAME, CRISP_TOKEN, DEFAULT_THEME };
