const BUILD_ENV = process.env.NEXT_PUBLIC_BUILD_ENV;
const IS_PRODUCTION = BUILD_ENV === "production";
const FULL_HOSTNAME = process.env.NEXT_PUBLIC_FULL_HOSTNAME;
const TAWK_PROPERTY_ID = process.env.NEXT_PUBLIC_TAWK_PROPERTY_ID;
const TAWK_WIDGET_ID = process.env.NEXT_PUBLIC_TAWK_WIDGET_ID;
const DEFAULT_THEME = "dark";
export { BUILD_ENV, IS_PRODUCTION, FULL_HOSTNAME, TAWK_PROPERTY_ID, TAWK_WIDGET_ID, DEFAULT_THEME };
